name: 🚀 Deploy Frontend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: 📂 Deploy via SFTP (Password Auth)
        uses: wlixcc/SFTP-Deploy-Action@v1.2
        with:
          server: ${{ secrets.SFTP_HOST }}
          port: 2298
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          local_path: ./dist
          remote_path: /home/core1/public_html
          args: "-o StrictHostKeyChecking=no"
